### ISSUE TITLE
Digest authentication does not work with uri containing escaped characters

### ISSUE THREAD

**Issue by gbittoun** [samizdatco/nginx-http-auth-digest#16]
I'm currently using NGINX with the digest authentication module. I've activated the autoindex on a folder and everything worked fine until I had a folder containing whitespace in its name. Everytime I tried to access it, the autentication failed.

I dumped the computed md5 in the error logs and compared it with the one sent by firefox, it was indeed different, but I figured out that the computed md5 was the one computed with the uri unescaped (eg "/test/abcd .txt" instead of "/test/abcd%20.txt").

I a currently trying to modify the nginx-http-auth-digest code to escape the url before computing hash, but I was wondering on how to properly do this. Moreover, there's maybe a way to configure NGINX and keeping raw uri when computing md5, so I won't have to modify your code, but I didn't find much informations on google.

If any of you can reproduce this bug and help find the best way to correct this, any answer will be appreciated.

Regards,

**Comment by erikdubbelboer** [comment]
I think this has been fixed in the latest version.
