### ISSUE TITLE
Digest Authentication fails on URLs with a querystring

### ISSUE THREAD

**Issue by agemmell** [samizdatco/nginx-http-auth-digest#18]
It appears the HttpAuthDigestModule cannot successfully authenticate on URLs that have a question mark at the end of them (and so anything with a querystring fails).  I get repeatedly challenged for a username and password despite entering in a correct one.

Perhaps it's something to do with my configuration?  I detailed my config in a previous issue here: https://github.com/samizdatco/nginx-http-auth-digest/issues/17

Is there anything I can do to fix this?

**Comment by erikdubbelboer** [comment]
Fixed in latest version.
