### ISSUE TITLE
stale=TRUE not added on expiring

### ISSUE THREAD

**Issue by bam80** [samizdatco/nginx-http-auth-digest#21]
If an expired nonce is used, shouldn't the server add stale=TRUE to the authentication header? Now, so that stale=TRUE is not added in the case, it's impossible to distinguish for client if the nonce is expired or credentials have changed on server side.
The problem arises when using client with libcurl digest auth implementation.

**Comment by erikdubbelboer** [comment]
Not sure when this was fixed but the module now adds `stale=true`.
