### ISSUE TITLE
satisfy should work with auth_digest just like auth_basic

### ISSUE THREAD

**Issue by tmcclure** [samizdatco/nginx-http-auth-digest#23]
The following config should allow access based on either a valid IP or a valid authenticated request:

```
satisfy any;

allow 127.0.0.1;
allow 10.0.0.0/16;

auth_digest somerealm;
auth_digest_user_file /path/to/file;

deny all;
```

It works correctly with auth_basic but not with auth_digest.

**Comment by root-ua** [comment]
I have the same problem. It doesn't work with 3rd party module auth_digest.

**Comment by erikdubbelboer** [comment]
This should work, see https://github.com/atomx/nginx-http-auth-digest/issues/10
