### ISSUE TITLE
username or password is rejected when compiled with nginx 1.4.4 and nginx 1.7.1

### ISSUE THREAD

**Issue by putnamhill** [samizdatco/nginx-http-auth-digest#24]
I suspect this is related to my using a version of nginx > 1.0.x.
#### browsers used:

Safari 7.0.1 (9537.73.11), Firefox 26, and Google Chrome 32
#### nginx -V

```
nginx version: nginx/1.4.4
built by gcc 4.7.3 (Ubuntu/Linaro 4.7.3-1ubuntu1)
configure arguments: --with-ipv6 --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --add-module=../echo-nginx-module --with-http_xslt_module --add-module=../nginx-http-auth-digest

nginx version: nginx/1.7.12
built by gcc 4.8.2 (Ubuntu 4.8.2-19ubuntu1)
TLS SNI support enabled
configure arguments: --with-debug --with-http_ssl_module --with-ipv6 --with-http_auth_request_module --add-module=../nginx-http-auth-digest --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log
```
#### login credentials:

username: fred
password: flintstone
realm: this is not for you
#### htdigest command:

``` bash
sudo htdigest -c /etc/nginx/passwd.digest 'this is not for you' fred
```
#### nginx configuration:

```
auth_digest_user_file /etc/nginx/passwd.digest;
location /private {
    auth_digest 'this is not for you';
    auth_digest_timeout 60s;
    auth_digest_expires 10s;
    auth_digest_replays 20;
}
```

Error Msg:

> The user name or password you entered for this area on putnamhill.net:80 was incorrect. Make sure you’re entering them correctly, and then try again.

**Comment by ArtemZ** [comment]
I can't get auth digest working on nginx 1.6 either, but I don't see any error message at all, it just keeps asking for credentials after I enter them into the login form.

Here is a log from wget http://paste.ubuntu.com/10706896/

**Comment by putnamhill** [comment]
Same result with nginx 1.7.12.

Here is my wget output:
http://paste.ubuntu.com/10707506/

**Comment by ArtemZ** [comment]
@putnamhill we built fork of this module from Erik Dubbelboer https://github.com/atomx/nginx-http-auth-digest and it seems to compile fine on nginx 1.6.2

**Comment by putnamhill** [comment]
Thank you! That does work. The above test link is now functional.

**Comment by erikdubbelboer** [comment]
Fixed in latest version.
