### ISSUE TITLE
html request with parameters not working

### ISSUE THREAD

**Issue by tljdebrouwer** [samizdatco/nginx-http-auth-digest#28]
Hi,

If I send a request like "index.html?test1=a&test2=b" without authentication enabled the request is successfully forwarded to my backend, if I enable auth_digest, I keep getting getting a request to login but it won't accept my password. Other pages are working. 

Is this desired behaviour? Is there anything I should add to my configuration files?

Thanks in advance,

Tom

Using nginx 1.8.0 and head nginx-http-auth-digest

**Comment by putnamhill** [comment]
You might want to try Erik Dubbelboer's fork https://github.com/atomx/nginx-http-auth-digest

It works for me compiled with 1.7.12. Try the following link with user fred password flintstone:
http://putnamhill.net/private/test.txt?test1=a&test2=b

**Comment by tljdebrouwer** [comment]
Thanks, that one works  :+1: !
