### ISSUE TITLE
invalid username or password in error log when digest expired

### ISSUE THREAD

**Issue by fffilimonov** [samizdatco/nginx-http-auth-digest#32]
There is a lot of record in error log when digest expired.
Actually it's a different cases when credentials are invalid and digest expired.
I don't see how to fix it.
Maybe change log severity?
Or make it configurable (log username or password or not).

**Comment by erikdubbelboer** [comment]
Fixed in https://github.com/samizdatco/nginx-http-auth-digest/commit/cd8641886c873cf543255aeda20d23e4cd603d05
